2022-01-31 21:31:31,005 INFO core.py Запущен сервер, порт для подключений: 7777, адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2022-01-31 21:31:31,020 INFO core.py Сервер запущен...
2022-01-31 21:31:38,145 INFO core.py Установлено соедение с ПК ('127.0.0.1', 52151)
2022-01-31 21:31:38,176 DEBUG core.py Получено сообщение {'action': 'presence', 'time': 1643643098.1454926, 'user': {'account_name': 'Guest'}}
2022-01-31 21:31:38,176 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1643643098.1454926, 'user': {'account_name': 'Guest'}}
2022-01-31 21:31:38,176 INFO core.py Cформирован ответ клиенту {'response': 200}
2022-01-31 21:31:38,176 DEBUG core.py Соединение с клиентом ('127.0.0.1', 52151) закрывается.
2022-01-31 21:35:27,233 INFO core.py Запущен сервер, порт для подключений: 7777, адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2022-01-31 21:35:27,233 INFO core.py Сервер запущен...
2022-01-31 21:35:30,145 INFO core.py Установлено соедение с ПК ('127.0.0.1', 52156)
2022-01-31 21:35:30,160 DEBUG core.py Получено сообщение {'action': 'presence', 'time': 1643643330.1453364, 'user': {'account_name': 'Guest'}}
2022-01-31 21:35:30,160 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1643643330.1453364, 'user': {'account_name': 'Guest'}}
2022-01-31 21:35:30,160 INFO core.py Cформирован ответ клиенту {'response': 200}
2022-01-31 21:35:30,160 DEBUG core.py Соединение с клиентом ('127.0.0.1', 52156) закрывается.
2022-01-31 21:40:44,425 INFO core.py Запущен сервер, порт для подключений: 7777, адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2022-01-31 21:40:44,503 DEBUG decos.py Была вызвана функция check_address_port_server c параметрами (<common.core.MessengerCore object at 0x000001D438C67760>,), {}. Вызов из модуля common.core. Вызов из функции main().Вызов из функции __init__
2022-01-31 21:40:44,503 INFO core.py Сервер запущен...
2022-01-31 21:40:48,410 INFO core.py Установлено соедение с ПК ('127.0.0.1', 52177)
2022-01-31 21:40:48,456 DEBUG core.py Получено сообщение {'action': 'presence', 'time': 1643643648.410059, 'user': {'account_name': 'Guest'}}
2022-01-31 21:40:48,456 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1643643648.410059, 'user': {'account_name': 'Guest'}}
2022-01-31 21:40:48,456 DEBUG decos.py Была вызвана функция process_client_message c параметрами (<common.core.MessengerCore object at 0x000001D438C67760>,), {}. Вызов из модуля common.core. Вызов из функции main().Вызов из функции start_server_listen
2022-01-31 21:40:48,456 INFO core.py Cформирован ответ клиенту {'response': 200}
2022-01-31 21:40:48,456 DEBUG core.py Соединение с клиентом ('127.0.0.1', 52177) закрывается.
2022-01-31 21:48:47,011 INFO core.py Запущен сервер, порт для подключений: 7777, адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2022-01-31 21:48:47,058 DEBUG decos.py Была вызвана функция check_address_port_server c параметрами (<common.core.MessengerCore object at 0x00000215D7717760>,), {}. Вызов из модуля common.core. Вызов из функции main().Вызов из функции __init__
2022-01-31 21:48:47,058 DEBUG decos.py Была вызвана функция __init__ c параметрами (<common.core.MessengerCore object at 0x00000215D7717760>,), {'start_server': True}. Вызов из модуля common.core. Вызов из функции main().Вызов из функции main
2022-01-31 21:48:47,058 INFO core.py Сервер запущен...
2022-01-31 21:48:50,339 INFO core.py Установлено соедение с ПК ('127.0.0.1', 52195)
2022-01-31 21:48:50,339 DEBUG core.py Получено сообщение {'action': 'presence', 'time': 1643644130.3397243, 'user': {'account_name': 'Guest'}}
2022-01-31 21:48:50,339 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1643644130.3397243, 'user': {'account_name': 'Guest'}}
2022-01-31 21:48:50,339 DEBUG decos.py Была вызвана функция process_client_message c параметрами (<common.core.MessengerCore object at 0x00000215D7717760>,), {}. Вызов из модуля common.core. Вызов из функции main().Вызов из функции start_server_listen
2022-01-31 21:48:50,339 INFO core.py Cформирован ответ клиенту {'response': 200}
2022-01-31 21:48:50,339 DEBUG core.py Соединение с клиентом ('127.0.0.1', 52195) закрывается.
2022-01-31 21:52:51,287 INFO core.py Запущен сервер, порт для подключений: 7777, адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2022-01-31 21:52:51,334 DEBUG decos.py Была вызвана функция check_address_port_server c параметрами (<common.core.MessengerCore object at 0x0000024DF8A18760>,). Вызов из модуля common.core. Вызов из функции main().Вызов из функции __init__
2022-01-31 21:52:51,334 DEBUG decos.py Была вызвана функция __init__ c параметрами (<common.core.MessengerCore object at 0x0000024DF8A18760>,), {'start_server': True}. Вызов из модуля common.core. Вызов из функции main().Вызов из функции main
2022-01-31 21:52:51,334 INFO core.py Сервер запущен...
2022-01-31 21:53:00,711 INFO core.py Установлено соедение с ПК ('127.0.0.1', 52203)
2022-01-31 21:53:00,742 DEBUG core.py Получено сообщение {'action': 'presence', 'time': 1643644380.7114375, 'user': {'account_name': 'Guest'}}
2022-01-31 21:53:00,742 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1643644380.7114375, 'user': {'account_name': 'Guest'}}
2022-01-31 21:53:00,742 DEBUG decos.py Была вызвана функция process_client_message c параметрами (<common.core.MessengerCore object at 0x0000024DF8A18760>,). Вызов из модуля common.core. Вызов из функции main().Вызов из функции start_server_listen
2022-01-31 21:53:00,742 INFO core.py Cформирован ответ клиенту {'response': 200}
2022-01-31 21:53:00,742 DEBUG core.py Соединение с клиентом ('127.0.0.1', 52203) закрывается.
2022-01-31 22:05:18,927 INFO core.py Запущен сервер, порт для подключений: 7777, адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2022-01-31 22:05:18,990 DEBUG decos.py Была вызвана функция check_address_port_server c параметрами (<common.core.MessengerCore object at 0x00000299A1527760>,). Вызов из модуля common.core. Вызов из функции main().Вызов из функции __init__
2022-01-31 22:05:18,990 DEBUG decos.py Была вызвана функция __init__ c параметрами (<common.core.MessengerCore object at 0x00000299A1527760>,), {'start_server': True}. Вызов из модуля common.core. Вызов из функции main().Вызов из функции main
2022-01-31 22:05:18,990 INFO core.py Сервер запущен...
2022-01-31 22:05:22,662 INFO core.py Установлено соедение с ПК ('127.0.0.1', 52238)
2022-01-31 22:05:22,677 DEBUG core.py Получено сообщение {'action': 'presence', 'time': 1643645122.6620274, 'user': {'account_name': 'Guest'}}
2022-01-31 22:05:22,677 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1643645122.6620274, 'user': {'account_name': 'Guest'}}
2022-01-31 22:05:22,677 DEBUG decos.py Была вызвана функция process_client_message c параметрами (<common.core.MessengerCore object at 0x00000299A1527760>,). Вызов из модуля common.core. Вызов из функции main().Вызов из функции start_server_listen
2022-01-31 22:05:22,677 INFO core.py Cформирован ответ клиенту {'response': 200}
2022-01-31 22:05:22,677 DEBUG core.py Соединение с клиентом ('127.0.0.1', 52238) закрывается.
2022-01-31 22:05:28,133 INFO core.py Установлено соедение с ПК ('127.0.0.1', 52239)
2022-01-31 22:05:28,149 DEBUG core.py Получено сообщение {'action': 'presence', 'time': 1643645128.1336484, 'user': {'account_name': 'Guest'}}
2022-01-31 22:05:28,149 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1643645128.1336484, 'user': {'account_name': 'Guest'}}
2022-01-31 22:05:28,149 DEBUG decos.py Была вызвана функция process_client_message c параметрами (<common.core.MessengerCore object at 0x00000299A1527760>,). Вызов из модуля common.core. Вызов из функции main().Вызов из функции start_server_listen
2022-01-31 22:05:28,149 INFO core.py Cформирован ответ клиенту {'response': 200}
2022-01-31 22:05:28,149 DEBUG core.py Соединение с клиентом ('127.0.0.1', 52239) закрывается.
